project:
  type: website
  output-dir: ../docs

website:
  title: "Félicie Lallement"
  site-url: https://feliciellm.github.io/design-portfolio/
  navbar:
    right:
      - about.qmd
      - icon: instagram
        href: https://www.instagram.com/design_felicie/
      - icon: github
        href: https://github.com/feliciellm/design-portfolio

format:
  html:
    theme: cosmo
    css: styles.css



