project:
  type: website
  output-dir: ../docs

website:
  title: "Mes projets"
  site-url: https://feliciellm.github.io/design-portfolio/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/feliciellm
      - icon: instagram
        href: https://twitter.com

format:
  html:
    theme: cosmo
    css: styles.css



